import {
  Client, Worker, Workflow, TaskRun, Approval, ActivityEvent,
  Integration, WorkspaceSettings, WorkflowTemplate,
  type WorkflowStep
} from './types';

// ============================================================
// CLIENTS
// ============================================================

export const clients: Client[] = [
  { id: 'client-1', name: 'Alder & Ash', industry: 'E-commerce', color: '#6B8F71' },
  { id: 'client-2', name: 'Goodfield Nutrition', industry: 'Consumer Products', color: '#C4883B' },
  { id: 'client-3', name: 'Meridian Learning', industry: 'Education', color: '#5B7BA6' },
];

// ============================================================
// WORKERS
// ============================================================

export const workers: Worker[] = [
  {
    id: 'worker-1',
    name: 'Campaign Analyst',
    role: 'Inspect campaign performance and identify noteworthy changes',
    description: 'Monitors selected campaigns across connected ad platforms, identifies anomalies, cost changes, and performance shifts. Prepares findings with supporting evidence for human review.',
    status: 'active',
    permissions: ['read_data', 'draft_outputs', 'create_tasks'],
    restrictedActions: ['Cannot change budgets', 'Cannot execute campaign changes', 'Cannot send external communications'],
    assignedWorkflows: ['wf-1', 'wf-4'],
    recentTaskCount: 14,
    successCount: 12,
    failureCount: 2,
    lastActivity: '2026-10-09T06:30:00Z',
    typicalOutputs: ['Findings', 'Supporting evidence', 'Suggested areas for investigation'],
    limits: ['Cannot change budgets or execute campaign changes'],
    configRevision: 3,
  },
  {
    id: 'worker-2',
    name: 'Report Assembler',
    role: 'Compile approved data and findings into reporting drafts',
    description: 'Collects approved data points, structured findings, and contextual metrics to produce formatted performance reports. Identifies missing data and flags gaps rather than inventing metrics.',
    status: 'active',
    permissions: ['read_data', 'draft_outputs'],
    restrictedActions: ['Cannot fabricate data', 'Cannot publish reports without approval', 'Cannot modify source data'],
    assignedWorkflows: ['wf-2'],
    recentTaskCount: 8,
    successCount: 7,
    failureCount: 1,
    lastActivity: '2026-10-09T05:15:00Z',
    typicalOutputs: ['Performance summaries', 'Data tables', 'Report drafts'],
    limits: ['Must identify missing data and must not invent metrics'],
    configRevision: 2,
  },
  {
    id: 'worker-3',
    name: 'Quality Reviewer',
    role: 'Check outputs for accuracy, completeness, and consistency',
    description: 'Reviews all workflow outputs before they reach approval. Checks for missing fields, inconsistent data, unsupported statements, formatting issues, and logical errors.',
    status: 'active',
    permissions: ['read_data', 'draft_outputs', 'create_tasks'],
    restrictedActions: ['Cannot override business decisions', 'Cannot approve outputs', 'Cannot modify finalized reports'],
    assignedWorkflows: ['wf-1', 'wf-2', 'wf-3'],
    recentTaskCount: 11,
    successCount: 10,
    failureCount: 1,
    lastActivity: '2026-10-09T07:00:00Z',
    typicalOutputs: ['Validation results', 'Corrections', 'Warnings'],
    limits: ['Does not automatically override business decisions'],
    configRevision: 1,
  },
  {
    id: 'worker-4',
    name: 'Client Update Drafter',
    role: 'Prepare client-facing explanations from approved findings',
    description: 'Transforms internal performance findings into clear, professional client-facing communications. Prepares draft messages and update summaries for human review before sending.',
    status: 'idle',
    permissions: ['read_data', 'draft_outputs'],
    restrictedActions: ['Cannot send external communications without approval', 'Cannot access raw campaign data', 'Cannot modify internal reports'],
    assignedWorkflows: ['wf-3'],
    recentTaskCount: 5,
    successCount: 5,
    failureCount: 0,
    lastActivity: '2026-10-08T16:45:00Z',
    typicalOutputs: ['Draft messages', 'Update summaries'],
    limits: ['Cannot send external communications without approval'],
    configRevision: 2,
  },
];

// ============================================================
// WORKFLOW TEMPLATES
// ============================================================

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Campaign Watch',
    description: 'Monitor campaigns and identify noteworthy changes',
    defaultSteps: [
      { id: 'step-1', name: 'Retrieve campaign data', description: 'Pull latest metrics from connected ad platforms' },
      { id: 'step-2', name: 'Validate data freshness', description: 'Check that data sources are current and complete' },
      { id: 'step-3', name: 'Analyze changes', description: 'Compare metrics against baselines and thresholds' },
      { id: 'step-4', name: 'Draft findings', description: 'Prepare observation summary with supporting evidence' },
      { id: 'step-5', name: 'Quality review', description: 'Check findings for accuracy and completeness' },
      { id: 'step-6', name: 'Human review', description: 'Route findings for approval' },
    ],
  },
  {
    id: 'tmpl-2',
    name: 'Performance Report',
    description: 'Collect data and prepare a structured reporting draft',
    defaultSteps: [
      { id: 'step-1', name: 'Gather metrics', description: 'Collect performance data from all connected sources' },
      { id: 'step-2', name: 'Validate inputs', description: 'Ensure all required metrics are available' },
      { id: 'step-3', name: 'Assemble report', description: 'Compile data into structured report format' },
      { id: 'step-4', name: 'Quality check', description: 'Review for formatting, accuracy, and completeness' },
      { id: 'step-5', name: 'Submit for review', description: 'Route report draft for human approval' },
    ],
  },
  {
    id: 'tmpl-3',
    name: 'Client Update Draft',
    description: 'Prepare a client-facing summary for human review',
    defaultSteps: [
      { id: 'step-1', name: 'Review approved findings', description: 'Read the latest approved internal reports' },
      { id: 'step-2', name: 'Draft client message', description: 'Transform findings into client-appropriate language' },
      { id: 'step-3', name: 'Quality review', description: 'Check tone, accuracy, and completeness' },
      { id: 'step-4', name: 'Human approval', description: 'Route draft for final approval before sending' },
    ],
  },
  {
    id: 'tmpl-4',
    name: 'Account Health Check',
    description: 'Verify data source availability and flag inconsistencies',
    defaultSteps: [
      { id: 'step-1', name: 'Check connections', description: 'Verify all integrations are active and responding' },
      { id: 'step-2', name: 'Validate data coverage', description: 'Ensure all expected data categories are present' },
      { id: 'step-3', name: 'Flag issues', description: 'Report missing, stale, or inconsistent data' },
      { id: 'step-4', name: 'Generate health report', description: 'Compile findings into a status summary' },
    ],
  },
];

// ============================================================
// WORKFLOWS
// ============================================================

export const initialWorkflows: Workflow[] = [
  {
    id: 'wf-1',
    name: 'Campaign Watch — Alder & Ash',
    description: 'Monitors Alder & Ash Google Ads campaigns and identifies noteworthy performance changes.',
    status: 'active',
    workerId: 'worker-1',
    clientId: 'client-1',
    template: 'tmpl-1',
    dataSourceIds: ['int-1', 'int-2'],
    approvalRequired: true,
    approvalRules: ['Findings with budget impact require approval', 'All recommendations require review'],
    schedule: 'Daily at 9:00 AM',
    lastRun: '2026-10-09T06:00:00Z',
    nextScheduledRun: '2026-10-10T06:00:00Z',
    recentRunStatus: 'needs_review',
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-10-09T06:30:00Z',
    thresholds: { cpaChangePercent: 15, budgetImpactMin: 100 },
    steps: [
      { id: 'wf1-s1', name: 'Retrieve campaign data', description: 'Pull latest metrics from Google Ads', status: 'completed', startedAt: '2026-10-09T06:00:00Z', completedAt: '2026-10-09T06:02:00Z', output: 'Retrieved 14 campaigns, 2,847 ad groups' },
      { id: 'wf1-s2', name: 'Validate data freshness', description: 'Check that data sources are current', status: 'completed', startedAt: '2026-10-09T06:02:00Z', completedAt: '2026-10-09T06:03:00Z', output: 'All sources current as of 2026-10-09 05:45 UTC' },
      { id: 'wf1-s3', name: 'Analyze changes', description: 'Compare against 7-day baselines', status: 'completed', startedAt: '2026-10-09T06:03:00Z', completedAt: '2026-10-09T06:12:00Z', output: 'CPA increased 23% for "Summer Collection" campaign. CTR stable. Impressions up 8%.' },
      { id: 'wf1-s4', name: 'Draft findings', description: 'Prepare observation summary', status: 'completed', startedAt: '2026-10-09T06:12:00Z', completedAt: '2026-10-09T06:18:00Z', output: 'Summary: Notable CPA increase detected in Summer Collection campaign. Supporting metrics assembled.' },
      { id: 'wf1-s5', name: 'Quality review', description: 'Check findings for accuracy', status: 'completed', startedAt: '2026-10-09T06:18:00Z', completedAt: '2026-10-09T06:22:00Z', output: 'Review passed. One minor formatting correction applied.' },
      { id: 'wf1-s6', name: 'Human review', description: 'Route findings for approval', status: 'needs_review', startedAt: '2026-10-09T06:22:00Z' },
    ],
  },
  {
    id: 'wf-2',
    name: 'Performance Report — Goodfield Nutrition',
    description: 'Compiles weekly performance data for Goodfield Nutrition into a structured report draft.',
    status: 'active',
    workerId: 'worker-2',
    clientId: 'client-2',
    template: 'tmpl-2',
    dataSourceIds: ['int-1', 'int-3'],
    approvalRequired: true,
    approvalRules: ['All report drafts require approval before distribution'],
    schedule: 'Weekly on Monday at 8:00 AM',
    lastRun: '2026-10-07T05:00:00Z',
    nextScheduledRun: '2026-10-14T05:00:00Z',
    recentRunStatus: 'completed',
    createdAt: '2026-09-20T14:00:00Z',
    updatedAt: '2026-10-07T05:45:00Z',
    steps: [
      { id: 'wf2-s1', name: 'Gather metrics', description: 'Collect from Google Ads and Meta Ads', status: 'completed', startedAt: '2026-10-07T05:00:00Z', completedAt: '2026-10-07T05:05:00Z', output: 'Collected metrics from 2 platforms' },
      { id: 'wf2-s2', name: 'Validate inputs', description: 'Check data completeness', status: 'completed', startedAt: '2026-10-07T05:05:00Z', completedAt: '2026-10-07T05:08:00Z', output: 'All metrics present' },
      { id: 'wf2-s3', name: 'Assemble report', description: 'Compile into report format', status: 'completed', startedAt: '2026-10-07T05:08:00Z', completedAt: '2026-10-07T05:25:00Z', output: 'Report draft generated with 4 sections, 12 metrics' },
      { id: 'wf2-s4', name: 'Quality check', description: 'Review formatting and accuracy', status: 'completed', startedAt: '2026-10-07T05:25:00Z', completedAt: '2026-10-07T05:30:00Z', output: 'Passed quality checks' },
      { id: 'wf2-s5', name: 'Submit for review', description: 'Route for approval', status: 'completed', startedAt: '2026-10-07T05:30:00Z', completedAt: '2026-10-07T05:30:00Z', output: 'Approved by team lead' },
    ],
  },
  {
    id: 'wf-3',
    name: 'Client Update Draft — Alder & Ash',
    description: 'Prepares a client-facing performance update based on approved internal findings.',
    status: 'active',
    workerId: 'worker-4',
    clientId: 'client-1',
    template: 'tmpl-3',
    dataSourceIds: [],
    approvalRequired: true,
    approvalRules: ['All external communications require approval'],
    lastRun: '2026-10-08T14:00:00Z',
    recentRunStatus: 'needs_review',
    createdAt: '2026-09-25T09:00:00Z',
    updatedAt: '2026-10-08T14:30:00Z',
    steps: [
      { id: 'wf3-s1', name: 'Review approved findings', description: 'Read latest approved reports', status: 'completed', startedAt: '2026-10-08T14:00:00Z', completedAt: '2026-10-08T14:05:00Z', output: 'Reviewed 2 approved findings from Campaign Watch' },
      { id: 'wf3-s2', name: 'Draft client message', description: 'Transform into client language', status: 'completed', startedAt: '2026-10-08T14:05:00Z', completedAt: '2026-10-08T14:18:00Z', output: 'Draft prepared: Weekly performance summary for Alder & Ash' },
      { id: 'wf3-s3', name: 'Quality review', description: 'Check tone and accuracy', status: 'completed', startedAt: '2026-10-08T14:18:00Z', completedAt: '2026-10-08T14:22:00Z', output: 'Passed with one suggested tone adjustment' },
      { id: 'wf3-s4', name: 'Human approval', description: 'Route for final approval', status: 'needs_review', startedAt: '2026-10-08T14:22:00Z' },
    ],
  },
  {
    id: 'wf-4',
    name: 'Account Health Check — Meridian Learning',
    description: 'Verifies data source connectivity and flags missing or inconsistent information for Meridian Learning.',
    status: 'active',
    workerId: 'worker-1',
    clientId: 'client-3',
    template: 'tmpl-4',
    dataSourceIds: ['int-2', 'int-4'],
    approvalRequired: false,
    approvalRules: [],
    schedule: 'Daily at 7:00 AM',
    lastRun: '2026-10-09T04:00:00Z',
    nextScheduledRun: '2026-10-10T04:00:00Z',
    recentRunStatus: 'failed',
    createdAt: '2026-09-28T11:00:00Z',
    updatedAt: '2026-10-09T04:15:00Z',
    steps: [
      { id: 'wf4-s1', name: 'Check connections', description: 'Verify integrations are active', status: 'completed', startedAt: '2026-10-09T04:00:00Z', completedAt: '2026-10-09T04:02:00Z', output: 'Google Analytics: Connected. HubSpot CRM: Needs reauthorization.' },
      { id: 'wf4-s2', name: 'Validate data coverage', description: 'Check data categories', status: 'failed', startedAt: '2026-10-09T04:02:00Z', completedAt: '2026-10-09T04:05:00Z', error: 'HubSpot CRM connection expired. Cannot validate CRM data coverage. Last successful sync: 2026-10-06.' },
      { id: 'wf4-s3', name: 'Flag issues', description: 'Report problems', status: 'pending' },
      { id: 'wf4-s4', name: 'Generate health report', description: 'Compile status summary', status: 'pending' },
    ],
  },
];

// ============================================================
// TASK RUNS
// ============================================================

export const initialTaskRuns: TaskRun[] = [
  {
    id: 'run-1',
    workflowId: 'wf-1',
    clientId: 'client-1',
    workerId: 'worker-1',
    name: 'Campaign Watch — Oct 9',
    status: 'needs_review',
    startedAt: '2026-10-09T06:00:00Z',
    updatedAt: '2026-10-09T06:22:00Z',
    executionDuration: 1320,
    isSimulated: true,
    steps: initialWorkflows[0].steps,
    output: 'CPA for Alder & Ash "Summer Collection" campaign increased 23% over the 7-day average. CTR remained stable at 2.1%. Impressions increased 8%. Recommended investigation: audience targeting changes made on Oct 7.',
  },
  {
    id: 'run-2',
    workflowId: 'wf-2',
    clientId: 'client-2',
    workerId: 'worker-2',
    name: 'Weekly Report — Goodfield Nutrition',
    status: 'completed',
    startedAt: '2026-10-07T05:00:00Z',
    updatedAt: '2026-10-07T05:30:00Z',
    completedAt: '2026-10-07T05:30:00Z',
    executionDuration: 1800,
    isSimulated: true,
    steps: initialWorkflows[1].steps,
    output: 'Weekly performance report compiled. ROAS: 3.2x (up from 2.8x). Total spend: $4,200. Conversions: 156. Report approved and filed.',
  },
  {
    id: 'run-3',
    workflowId: 'wf-3',
    clientId: 'client-1',
    workerId: 'worker-4',
    name: 'Client Update — Alder & Ash',
    status: 'needs_review',
    startedAt: '2026-10-08T14:00:00Z',
    updatedAt: '2026-10-08T14:22:00Z',
    executionDuration: 1320,
    isSimulated: true,
    steps: initialWorkflows[2].steps,
    output: 'Client update draft prepared covering weekly performance highlights and the CPA increase in Summer Collection campaign.',
  },
  {
    id: 'run-4',
    workflowId: 'wf-4',
    clientId: 'client-3',
    workerId: 'worker-1',
    name: 'Health Check — Meridian Learning',
    status: 'failed',
    startedAt: '2026-10-09T04:00:00Z',
    updatedAt: '2026-10-09T04:05:00Z',
    executionDuration: 300,
    isSimulated: true,
    steps: initialWorkflows[3].steps,
    error: 'HubSpot CRM connection expired. Cannot validate CRM data coverage. Last successful sync: 2026-10-06.',
  },
  {
    id: 'run-5',
    workflowId: 'wf-1',
    clientId: 'client-1',
    workerId: 'worker-1',
    name: 'Campaign Watch — Oct 8',
    status: 'completed',
    startedAt: '2026-10-08T06:00:00Z',
    updatedAt: '2026-10-08T06:20:00Z',
    completedAt: '2026-10-08T06:20:00Z',
    executionDuration: 1200,
    isSimulated: true,
    steps: [
      { id: 'r5-s1', name: 'Retrieve campaign data', description: 'Pull latest metrics', status: 'completed', startedAt: '2026-10-08T06:00:00Z', completedAt: '2026-10-08T06:02:00Z', output: 'Retrieved 14 campaigns' },
      { id: 'r5-s2', name: 'Validate data freshness', description: 'Check sources', status: 'completed', startedAt: '2026-10-08T06:02:00Z', completedAt: '2026-10-08T06:03:00Z', output: 'All current' },
      { id: 'r5-s3', name: 'Analyze changes', description: 'Compare baselines', status: 'completed', startedAt: '2026-10-08T06:03:00Z', completedAt: '2026-10-08T06:10:00Z', output: 'No significant changes detected' },
      { id: 'r5-s4', name: 'Draft findings', description: 'Prepare summary', status: 'completed', startedAt: '2026-10-08T06:10:00Z', completedAt: '2026-10-08T06:15:00Z', output: 'Stable performance across all campaigns' },
      { id: 'r5-s5', name: 'Quality review', description: 'Check accuracy', status: 'completed', startedAt: '2026-10-08T06:15:00Z', completedAt: '2026-10-08T06:18:00Z', output: 'Passed' },
      { id: 'r5-s6', name: 'Human review', description: 'Route for approval', status: 'completed', startedAt: '2026-10-08T06:18:00Z', completedAt: '2026-10-08T06:20:00Z', output: 'Approved — no action needed' },
    ],
    output: 'All campaigns within normal parameters. No action required.',
  },
  {
    id: 'run-6',
    workflowId: 'wf-2',
    clientId: 'client-2',
    workerId: 'worker-2',
    name: 'Weekly Report — Sep 30',
    status: 'completed',
    startedAt: '2026-09-30T05:00:00Z',
    updatedAt: '2026-09-30T05:28:00Z',
    completedAt: '2026-09-30T05:28:00Z',
    executionDuration: 1680,
    isSimulated: true,
    steps: [],
    output: 'Weekly report compiled and approved. ROAS: 2.8x. Total spend: $3,900.',
  },
  {
    id: 'run-7',
    workflowId: 'wf-4',
    clientId: 'client-3',
    workerId: 'worker-1',
    name: 'Health Check — Oct 8',
    status: 'completed',
    startedAt: '2026-10-08T04:00:00Z',
    updatedAt: '2026-10-08T04:12:00Z',
    completedAt: '2026-10-08T04:12:00Z',
    executionDuration: 720,
    isSimulated: true,
    steps: [],
    output: 'All connections healthy. Data coverage complete.',
  },
  {
    id: 'run-8',
    workflowId: 'wf-3',
    clientId: 'client-1',
    workerId: 'worker-4',
    name: 'Client Update — Oct 1',
    status: 'completed',
    startedAt: '2026-10-01T14:00:00Z',
    updatedAt: '2026-10-01T14:25:00Z',
    completedAt: '2026-10-01T14:25:00Z',
    executionDuration: 1500,
    isSimulated: true,
    steps: [],
    output: 'Client update approved and filed.',
  },
];

// ============================================================
// APPROVALS
// ============================================================

export const initialApprovals: Approval[] = [
  {
    id: 'appr-1',
    taskRunId: 'run-1',
    workflowId: 'wf-1',
    workerId: 'worker-1',
    clientId: 'client-1',
    proposedAction: 'Approve performance findings',
    description: 'Campaign Watch identified a 23% CPA increase in the Alder & Ash "Summer Collection" campaign. The summary includes supporting metrics and a suggested investigation area.',
    evidence: 'CPA rose from $12.40 to $15.26 (23% increase) over 7 days. CTR stable at 2.1%. Impressions up 8%. Audience targeting was modified on Oct 7. The increase correlates with the targeting change but causation is not confirmed.',
    proposedContent: 'Performance Alert: Alder & Ash\n\nThe "Summer Collection" campaign CPA has increased 23% over the past 7 days ($12.40 → $15.26). This exceeds the 15% threshold configured for this workflow.\n\nKey observations:\n• CTR remains stable at 2.1%\n• Impressions increased 8%\n• Audience targeting was modified on Oct 7\n\nSuggested next step: Review the Oct 7 targeting changes and assess whether the audience expansion is delivering qualified traffic.\n\nNote: This is an observation. The system has not determined whether the targeting change caused the CPA increase.',
    reason: 'Findings with budget impact require approval',
    status: 'pending',
    createdAt: '2026-10-09T06:22:00Z',
  },
  {
    id: 'appr-2',
    taskRunId: 'run-3',
    workflowId: 'wf-3',
    workerId: 'worker-4',
    clientId: 'client-1',
    proposedAction: 'Approve client update draft',
    description: 'A client-facing performance update has been drafted for Alder & Ash, covering the weekly highlights and the recent CPA increase in the Summer Collection campaign.',
    evidence: 'Based on approved Campaign Watch findings from Oct 8–9. The draft summarizes performance in client-appropriate language and includes the CPA observation with appropriate caveats.',
    proposedContent: 'Hi Alder & Ash team,\n\nHere\'s your weekly performance summary:\n\nOverall, your campaigns are performing well. Impressions are up 8% this week, and click-through rates remain steady.\n\nOne area worth noting: the "Summer Collection" campaign has seen a cost increase of about 23% per conversion over the past week. We\'re looking into whether recent audience adjustments contributed to this and will have a recommendation by end of week.\n\nAll other campaigns are within normal ranges. Let us know if you have questions.\n\nBest,\nNorthstar Growth Team',
    reason: 'All external communications require approval',
    status: 'pending',
    createdAt: '2026-10-08T14:22:00Z',
  },
  {
    id: 'appr-3',
    taskRunId: 'run-2',
    workflowId: 'wf-2',
    workerId: 'worker-2',
    clientId: 'client-2',
    proposedAction: 'Approve performance report',
    description: 'Weekly performance report for Goodfield Nutrition has been compiled and quality-checked.',
    evidence: 'ROAS: 3.2x (up from 2.8x). Total spend: $4,200. Conversions: 156. All metrics verified against source data.',
    proposedContent: 'Goodfield Nutrition — Weekly Performance Report (Sep 30 – Oct 6)\n\nHighlights:\n• ROAS improved to 3.2x (previous week: 2.8x)\n• Total ad spend: $4,200\n• Conversions: 156 (+12% week-over-week)\n• Top campaign: "Fall Wellness Bundle" — ROAS 4.1x\n\nNo issues flagged. All data sources current.',
    reason: 'All report drafts require approval before distribution',
    status: 'approved',
    createdAt: '2026-10-07T05:30:00Z',
    decidedAt: '2026-10-07T09:15:00Z',
    decidedBy: 'Sarah Chen',
  },
  {
    id: 'appr-4',
    taskRunId: 'run-8',
    workflowId: 'wf-3',
    workerId: 'worker-4',
    clientId: 'client-1',
    proposedAction: 'Approve client update draft',
    description: 'Client update for Alder & Ash covering Sep 24–30 performance.',
    evidence: 'Based on approved findings. All metrics stable during this period.',
    reason: 'All external communications require approval',
    status: 'approved',
    createdAt: '2026-10-01T14:22:00Z',
    decidedAt: '2026-10-01T15:00:00Z',
    decidedBy: 'Sarah Chen',
  },
];

// ============================================================
// ACTIVITY EVENTS
// ============================================================

export const initialActivityEvents: ActivityEvent[] = [
  { id: 'evt-1', type: 'workflow_started', description: 'Campaign Watch started for Alder & Ash', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:00:00Z', status: 'info' },
  { id: 'evt-2', type: 'data_retrieved', description: 'Retrieved 14 campaigns, 2,847 ad groups from Google Ads', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:02:00Z', status: 'success' },
  { id: 'evt-3', type: 'validation_passed', description: 'Data freshness validation passed — all sources current', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:03:00Z', status: 'success' },
  { id: 'evt-4', type: 'step_completed', description: 'Analysis complete: CPA increase 23% detected in Summer Collection', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:12:00Z', status: 'warning' },
  { id: 'evt-5', type: 'summary_generated', description: 'Findings summary drafted with supporting evidence', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:18:00Z', status: 'success' },
  { id: 'evt-6', type: 'output_corrected', description: 'Quality review applied one formatting correction', workflowId: 'wf-1', workerId: 'worker-3', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:22:00Z', status: 'info' },
  { id: 'evt-7', type: 'approval_requested', description: 'Performance findings routed for human approval', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-1', timestamp: '2026-10-09T06:22:00Z', status: 'info' },
  { id: 'evt-8', type: 'workflow_failed', description: 'Account Health Check failed — HubSpot CRM connection expired', workflowId: 'wf-4', workerId: 'worker-1', clientId: 'client-3', taskRunId: 'run-4', timestamp: '2026-10-09T04:05:00Z', status: 'error', details: 'HubSpot CRM connection needs reauthorization. Last successful sync: Oct 6, 2026.' },
  { id: 'evt-9', type: 'workflow_started', description: 'Account Health Check started for Meridian Learning', workflowId: 'wf-4', workerId: 'worker-1', clientId: 'client-3', taskRunId: 'run-4', timestamp: '2026-10-09T04:00:00Z', status: 'info' },
  { id: 'evt-10', type: 'workflow_started', description: 'Client Update Draft started for Alder & Ash', workflowId: 'wf-3', workerId: 'worker-4', clientId: 'client-1', taskRunId: 'run-3', timestamp: '2026-10-08T14:00:00Z', status: 'info' },
  { id: 'evt-11', type: 'summary_generated', description: 'Client update draft prepared for Alder & Ash', workflowId: 'wf-3', workerId: 'worker-4', clientId: 'client-1', taskRunId: 'run-3', timestamp: '2026-10-08T14:18:00Z', status: 'success' },
  { id: 'evt-12', type: 'approval_requested', description: 'Client update draft routed for approval', workflowId: 'wf-3', workerId: 'worker-4', clientId: 'client-1', taskRunId: 'run-3', timestamp: '2026-10-08T14:22:00Z', status: 'info' },
  { id: 'evt-13', type: 'workflow_completed', description: 'Weekly Report completed for Goodfield Nutrition', workflowId: 'wf-2', workerId: 'worker-2', clientId: 'client-2', taskRunId: 'run-2', timestamp: '2026-10-07T05:30:00Z', status: 'success' },
  { id: 'evt-14', type: 'approval_granted', description: 'Performance report approved by Sarah Chen', workflowId: 'wf-2', workerId: 'worker-2', clientId: 'client-2', taskRunId: 'run-2', timestamp: '2026-10-07T09:15:00Z', status: 'success' },
  { id: 'evt-15', type: 'workflow_completed', description: 'Campaign Watch completed — no issues found', workflowId: 'wf-1', workerId: 'worker-1', clientId: 'client-1', taskRunId: 'run-5', timestamp: '2026-10-08T06:20:00Z', status: 'success' },
  { id: 'evt-16', type: 'workflow_completed', description: 'Account Health Check completed — all healthy', workflowId: 'wf-4', workerId: 'worker-1', clientId: 'client-3', taskRunId: 'run-7', timestamp: '2026-10-08T04:12:00Z', status: 'success' },
  { id: 'evt-17', type: 'approval_granted', description: 'Client update approved by Sarah Chen', workflowId: 'wf-3', workerId: 'worker-4', clientId: 'client-1', taskRunId: 'run-8', timestamp: '2026-10-01T15:00:00Z', status: 'success' },
];

// ============================================================
// INTEGRATIONS
// ============================================================

export const initialIntegrations: Integration[] = [
  {
    id: 'int-1',
    name: 'Google Ads',
    provider: 'Google',
    category: 'Advertising',
    status: 'connected',
    description: 'Access campaign performance data, ad group metrics, keyword performance, and budget information from Google Ads accounts.',
    dataCategories: ['Campaign metrics', 'Ad group performance', 'Keyword data', 'Budget tracking', 'Conversion data'],
    dependentWorkflows: ['wf-1', 'wf-2'],
    lastSync: '2026-10-09T05:45:00Z',
    connectedAt: '2026-09-15T10:30:00Z',
    setupNotes: 'Demo connection — does not access a real Google Ads account.',
  },
  {
    id: 'int-2',
    name: 'Google Analytics',
    provider: 'Google',
    category: 'Analytics',
    status: 'connected',
    description: 'Access website traffic, user behavior, conversion paths, and audience data from Google Analytics properties.',
    dataCategories: ['Traffic data', 'User behavior', 'Conversion paths', 'Audience segments', 'Page performance'],
    dependentWorkflows: ['wf-1', 'wf-4'],
    lastSync: '2026-10-09T05:30:00Z',
    connectedAt: '2026-09-15T10:45:00Z',
    setupNotes: 'Demo connection — does not access a real Google Analytics property.',
  },
  {
    id: 'int-3',
    name: 'Meta Ads',
    provider: 'Meta',
    category: 'Advertising',
    status: 'connected',
    description: 'Access campaign data, audience insights, and performance metrics from Meta advertising accounts (Facebook and Instagram).',
    dataCategories: ['Campaign metrics', 'Audience insights', 'Ad creative performance', 'Conversion tracking'],
    dependentWorkflows: ['wf-2'],
    lastSync: '2026-10-09T04:00:00Z',
    connectedAt: '2026-09-20T14:15:00Z',
    setupNotes: 'Demo connection — does not access a real Meta Ads account.',
  },
  {
    id: 'int-4',
    name: 'HubSpot CRM',
    provider: 'HubSpot',
    category: 'CRM',
    status: 'needs_attention',
    description: 'Access contact records, deal pipelines, and customer interaction history from HubSpot CRM.',
    dataCategories: ['Contact records', 'Deal pipelines', 'Activity history', 'Lead scoring'],
    dependentWorkflows: ['wf-4'],
    lastSync: '2026-10-06T12:00:00Z',
    connectedAt: '2026-09-28T11:30:00Z',
    setupNotes: 'Demo connection — does not access a real HubSpot account.',
    attentionMessage: 'Connection authorization has expired. Please reauthorize to resume data sync. Last successful sync: October 6, 2026.',
  },
];

// ============================================================
// WORKSPACE SETTINGS
// ============================================================

export const initialSettings: WorkspaceSettings = {
  name: 'Northstar Growth',
  organization: 'Northstar Growth Agency',
  defaultApprovalMode: 'draft_only',
  internalTasksRequireApproval: true,
  externalMessagesRequireApproval: true,
  campaignChangesProhibited: true,
  notificationsEnabled: true,
  emailDigest: 'daily',
};
